lab var	pa_id	"PA ID"
lab var	region	"Region"
lab var	round	"Batch"
lab var	year	"Year"
lab var	name_assessor	"Assessor Name"
lab var	date	"Date"
lab var	start_time	"Start Time"
lab var	end_time	"End Time"
lab var	duration	"Duration"
lab var	type_assessed	"Assessment Type"
lab var	country	"Country"
lab var	code	"Code"
lab var	business_name	"Business Name"
lab var	zone	"Zone"
lab var	woreda	"Woreda"
lab var	telephone	"Telephone"
lab var	email	"Email"
lab var	contact_person	"Contact Person"
lab var	year_estabilished	"Estabilishment Year"
lab var	employment_male	"Number of Male Employed"
lab var	employment_female	"Number of Female Employed"	
lab var	employment_total	"Total Number Employed"
lab var	agency_amount	"Amount Borrowed-Agency"
lab var	informal_amount	"Amount Borrowed-Informal"
lab var	education	"Education Level of Contact"
lab var	experience	"Experience in Years"
lab var	training	"Training"
lab var	staffing	"Staffing"
lab var	customer_service	"Customer Service"
lab var	housing	"Housing"
lab var	poultry_prtection_inputs	"Poultry Protection Inputs"
lab var	feed_and_feeding	"Feed and Feeding"
lab var	water_source_use	"Water Source and Use"
lab var	chicken_breed_quality	"Checken Breed Quality"
lab var	poultry_pests	"Poultry Pests"
lab var	farm_hygen	"Farm Hyegen"
lab var	annual_plan	"Annual Plan"
lab var	income_source	"Income Source"
lab var	financial_reliability	"Financial Reliability"
lab var	competition	"Competition"
lab var	promotion	"Promotion"
lab var	price_risk	"Price Risk"
lab var	supply_shortage	"Supply Shortage"
lab var	working_capital	"Working Capital"
lab var	financial_records	"Financial Records"
lab var	environmental_threats	"Environmental Theats"
lab var	mitigation_emvironmental	"Environmental Mitigation"
lab var	health_and_safety	"Health and Safety"
lab var	mgmt_capability_score	"Management Capability"
lab var	inst_competency_score	"Competency"
lab var	bus_knowledge_score	"Business Knowledge"
lab var	mark_potential_score	"Market Potential"	
lab var	fin_management_score	"Financial Management"
lab var	env_compliance_score	"Environmental Compliance"
lab var	average_score	"Average Score"
lab var	prod_cycle	"Production Cycle"
lab var	num_chicks_sold_farm	"Number of Chicken Sold to Farmer"
lab var	num_chicks_sold_gov_agent	"Number of Chicken Sold to Government Agenc"
lab var	num_chicks_sold_trader	"Number of Chicken Sold to Trader"
lab var	num_chicks_sold_vill_agents	"Number of Chicken Sold to Village Agent"
lab var	num_chicks_sold_other	"Number of Chicken Sold to Other"
lab var	num_chicks_sold_total	"Chickens Sold Total"
lab var	turn_over_farm	"Turnover from Farmer"
lab var	turn_over_gov_agent	"Turnover from Government Agent"
lab var	turn_over_trader	"Turnover from Trader"
lab var	turn_over_vill_agents	"Turnover from Village Agents"
lab var	turn_over_other	"Turnover from Other"
lab var	turn_over_total	"Total Turnover"
lab var	sold_to_unique_farmers	"Number of unique farmers sold"
lab var	contact_gender	"Contact Gender"
lab var	have_license	"Have License"
lab var	have_tin	"Have TIN"
lab var	contact_designation	"Contact Designation"
lab var	legal_formation	"Legal Formation"
lab var	avail_water	"Availability of Water"
lab var	avail_input_store	"Availability of Input Water"
lab var	avail_electricity	"Availability of Electricity"
lab var	avail_generator	"Availability of Generator"
lab var	avail_heating	"Availability of Heating"
lab var	agency_access_loan	"Access to Agency Loan	"
lab var	agency_lender_type	"Type of Agency Loan"
lab var	informal_access_loan	"Access to Informal Loan"
lab var	informal_lender_type	"Type of Infomral Loan"
lab var	contact_educ_cat	"Conatct Education"
lab var	hh_head_owner	"Household Owner Head"
lab var	train_given_by	"Provider of Training"
lab var	train_satisfaction	"Satisfaction of Training"
lab var	train_decision	"Decision to Participate to Training"
lab var	water_supply_man	"Supply of Water by Man"
lab var	water_supply_woman	"Supply of Water by Woman"
lab var	water_supply_children	"Supply of Water by Children"
lab var	water_supply_all	"Supply of Water by All"
lab var	source_prot_inputs	"Source of protection Inputs"
lab var	get_business_advice	"Get Business Advices"
lab var	access_poultry_mart	"Access to Poultry Markets"
lab var	finance_challenge1	"Finance Challenge 1"
lab var	finance_challenge2	"Finance Challenge 2"
lab var	finance_challenge3	"Finance Challenge 3"
lab var	finance_challenge4	"Finance Challenge 4"
